// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewWallet struct {
	Address string `json:"address"`
}

type Query struct {
}

type TransferResult struct {
	FromAddress string `json:"fromAddress"`
	ToAddress   string `json:"toAddress"`
	Amount      int32  `json:"amount"`
}

type Wallet struct {
	Address string `json:"address"`
	Balance int32  `json:"balance"`
}
